management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState

spring:
  kafka:
    consumer:
      bootstrap-servers: broker:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

teams:
  endpoint: http://host.docker.internal:28881
  path: /webhookb2/IncomingWebhook
  connectTimeout: 30000
  readTimeout: 30000

