management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState

spring:
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/sample
    username: user
    password: pass
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  kafka:
    consumer:
      bootstrap-servers: broker:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

teams:
  endpoint: http://host.docker.internal:28881
  path: /webhookb2/IncomingWebhook
  connectTimeout: 30000
  readTimeout: 30000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

togglz:
  features:
    NEW_PRODUCT:
      enabled: false
